//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ilen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warehouse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Warehouse()
        {
            this.MaterialOffs = new HashSet<MaterialOff>();
            this.MaterialProds = new HashSet<MaterialProd>();
        }
    
        public int ID { get; set; }
        public int Info { get; set; }
        public int Count { get; set; }
        public decimal Price { get; set; }
        public System.DateTime AdDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialOff> MaterialOffs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialProd> MaterialProds { get; set; }
        public virtual Post_Material Post_Material { get; set; }

        public override string ToString()
        {
            return Post_Material.Material.MaterialName;
        }
    }
}
